In [26]:
import pandas as pd
from pathlib import Path
import os
from camara_deputados.ingestion.data_loader import DataLoader

In [27]:
#instâncias

bronze = DataLoader('bronze')

In [28]:
dfs_bronze = bronze.carregar_parquets()

📂 Lendo dados da camada bronze: /mnt/d/GabrielaTorres/estudos/Univesp_Projetos/pi_camara_deputados/notebooks/../data/bronze

✅ deputados_detalhamento: 513 linhas, 34 colunas
✅ deputados_frentes: 131244 linhas, 6 colunas
✅ deputados_lista: 513 linhas, 10 colunas
✅ frentes: 100 linhas, 5 colunas
✅ frentes_detalhamento: 100 linhas, 22 colunas
✅ partidos: 15 linhas, 5 colunas
✅ partidos_detalhamento: 15 linhas, 23 colunas
✅ proposicoes: 60 linhas, 10 colunas
✅ proposicoes_autores: 57 linhas, 8 colunas
✅ proposicoes_detalhamento: 60 linhas, 36 colunas
✅ proposicoes_temas: 62 linhas, 5 colunas
✅ proposicoes_votacoes: 271 linhas, 13 colunas
✅ tipos_proposicao: 544 linhas, 5 colunas
✅ votacoes_detalhamento: 271 linhas, 21 colunas
✅ votacoes_orientacao: 399 linhas, 7 colunas

🎯 Carregamento finalizado.

In [29]:
def analisar_dfs(dfs):
    resultado = []

    for nome_tabela, df in dfs.items():
        for coluna in df.columns:
            
            total = len(df)
            nulos = df[coluna].isnull().sum()
            
            resultado.append({
                "tabela": nome_tabela,
                "coluna": coluna,
                "tipo": df[coluna].dtype,
                "nulos": nulos,
                "%_nulos": nulos / total,
                "unicos": df[coluna].astype(str).nunique(),
                "total_linhas": total
            })

    return pd.DataFrame(resultado)

In [30]:
df_analise = analisar_dfs(dfs_bronze)

In [32]:
df_analise.sample(10)

,tabela,coluna,tipo,nulos,%_nulos,unicos,total_linhas
68,frentes_detalhamento,coordenador.nome,str,0,0.000000,86,100
52,frentes,titulo,str,0,0.000000,100,100
3,deputados_detalhamento,cpf,str,0,0.000000,513,513
26,deputados_detalhamento,ultimoStatus.gabinete.andar,str,81,0.157895,8,513
187,votacoes_detalhamento,uriOrgao,str,0,0.000000,16,271
189,votacoes_detalhamento,uriEvento,str,65,0.239852,64,271
145,proposicoes_detalhamento,statusProposicao.siglaOrgao,str,2,0.033333,7,60
57,frentes_detalhamento,titulo,str,0,0.000000,100,100
195,votacoes_detalhamento,efeitosRegistrados,object,0,0.000000,72,271
48,deputados_lista,email,str,0,0.000000,513,513

In [22]:
df_analise[df_analise["tabela"] == "deputados_detalhamento"]

                    tabela  ... total_linhas
0   deputados_detalhamento  ...          513
1   deputados_detalhamento  ...          513
2   deputados_detalhamento  ...          513
3   deputados_detalhamento  ...          513
4   deputados_detalhamento  ...          513
5   deputados_detalhamento  ...          513
6   deputados_detalhamento  ...          513
7   deputados_detalhamento  ...          513
8   deputados_detalhamento  ...          513
9   deputados_detalhamento  ...          513
10  deputados_detalhamento  ...          513
11  deputados_detalhamento  ...          513
12  deputados_detalhamento  ...          513
13  deputados_detalhamento  ...          513
14  deputados_detalhamento  ...          513
15  deputados_detalhamento  ...          513
16  deputados_detalhamento  ...          513
17  deputados_detalhamento  ...          513
18  deputados_detalhamento  ...          513
19  deputados_detalhamento  ...          513
20  deputados_detalhamento  ...          513
21  deputados_detalhamento  ...          513
22  deputados_detalhamento  ...          513
23  deputados_detalhamento  ...          513
24  deputados_detalhamento  ...          513
25  deputados_detalhamento  ...          513
26  deputados_detalhamento  ...          513
27  deputados_detalhamento  ...          513
28  deputados_detalhamento  ...          513
29  deputados_detalhamento  ...          513
30  deputados_detalhamento  ...          513
31  deputados_detalhamento  ...          513
32  deputados_detalhamento  ...          513
33  deputados_detalhamento  ...          513

[34 rows x 7 columns]

In [23]:
df_analise[df_analise['tabela'] == 'deputados_lista']

             tabela         coluna  ... unicos  total_linhas
40  deputados_lista             id  ...    513           513
41  deputados_lista            uri  ...    513           513
42  deputados_lista           nome  ...    513           513
43  deputados_lista   siglaPartido  ...     21           513
44  deputados_lista     uriPartido  ...     21           513
45  deputados_lista        siglaUf  ...     27           513
46  deputados_lista  idLegislatura  ...      1           513
47  deputados_lista        urlFoto  ...    513           513
48  deputados_lista          email  ...    513           513
49  deputados_lista  data_extracao  ...      1           513

[10 rows x 7 columns]

In [24]:
df_analise[df_analise['tabela']=='frentes']

     tabela         coluna            tipo  ...  %_nulos  unicos  total_linhas
50  frentes             id           int64  ...      0.0     100           100
51  frentes            uri             str  ...      0.0     100           100
52  frentes         titulo             str  ...      0.0     100           100
53  frentes  idLegislatura           int64  ...      0.0       1           100
54  frentes  data_extracao  datetime64[us]  ...      0.0       1           100

[5 rows x 7 columns]

In [7]:
df_analise[df_analise['tabela']=='partidos']

,tabela,coluna,tipo,nulos,%_nulos,unicos,total_linhas
77,partidos,id,int64,0,0.0,15,15
78,partidos,sigla,str,0,0.0,15,15
79,partidos,nome,str,0,0.0,15,15
80,partidos,uri,str,0,0.0,15,15
81,partidos,data_extracao,datetime64[us],0,0.0,1,15

In [10]:
df_analise[df_analise['tabela'].isin(['proposicoes','proposicoes_detalhamento'])]

,tabela,coluna,tipo,nulos,%_nulos,unicos,total_linhas
105,proposicoes,id,int64,0,0.000000,60,60
106,proposicoes,uri,str,0,0.000000,60,60
107,proposicoes,siglaTipo,str,0,0.000000,7,60
108,proposicoes,codTipo,int64,0,0.000000,13,60
109,proposicoes,numero,int64,0,0.000000,41,60
110,proposicoes,ano,int64,0,0.000000,4,60
111,proposicoes,ementa,str,0,0.000000,58,60
112,proposicoes,dataApresentacao,str,0,0.000000,44,60
113,proposicoes,ano_ref,int64,0,0.000000,4,60
114,proposicoes,data_extracao,datetime64[us],0,0.000000,1,60
123,proposicoes_detalhamento,id,int64,0,0.000000,60,60
124,proposicoes_detalhamento,uri,str,0,0.000000,60,60
125,proposicoes_detalhamento,siglaTipo,str,0,0.000000,7,60
126,proposicoes_detalhamento,codTipo,int64,0,0.000000,13,60
127,proposicoes_detalhamento,numero,int64,0,0.000000,41,60
128,proposicoes_detalhamento,ano,int64,0,0.000000,4,60
129,proposicoes_detalhamento,ementa,str,0,0.000000,58,60
130,proposicoes_detalhamento,dataApresentacao,str,0,0.000000,44,60
131,proposicoes_detalhamento,uriOrgaoNumerador,str,35,0.583333,8,60
132,proposicoes_detalhamento,uriAutores,str,0,0.000000,60,60
133,proposicoes_detalhamento,descricaoTipo,str,0,0.000000,13,60
134,proposicoes_detalhamento,ementaDetalhada,str,20,0.333333,5,60
135,proposicoes_detalhamento,keywords,str,20,0.333333,24,60
136,proposicoes_detalhamento,uriPropPrincipal,object,60,1.000000,0,60
137,proposicoes_detalhamento,uriPropAnterior,object,60,1.000000,0,60
138,proposicoes_detalhamento,uriPropPosterior,str,58,0.966667,2,60
139,proposicoes_detalhamento,urlInteiroTeor,str,4,0.066667,56,60
140,proposicoes_detalhamento,urnFinal,object,60,1.000000,0,60
141,proposicoes_detalhamento,texto,object,60,1.000000,0,60
142,proposicoes_detalhamento,justificativa,object,60,1.000000,0,60
143,proposicoes_detalhamento,statusProposicao.dataHora,str,2,0.033333,45,60
144,proposicoes_detalhamento,statusProposicao.sequencia,float64,2,0.033333,28,60
145,proposicoes_detalhamento,statusProposicao.siglaOrgao,str,2,0.033333,7,60
146,proposicoes_detalhamento,statusProposicao.uriOrgao,str,0,0.000000,8,60
147,proposicoes_detalhamento,statusProposicao.uriUltimoRelator,str,37,0.616667,21,60
148,proposicoes_detalhamento,statusProposicao.regime,str,0,0.000000,7,60
149,proposicoes_detalhamento,statusProposicao.descricaoTramitacao,str,2,0.033333,12,60
150,proposicoes_detalhamento,statusProposicao.codTipoTramitacao,str,2,0.033333,12,60
151,proposicoes_detalhamento,statusProposicao.descricaoSituacao,str,23,0.383333,14,60
152,proposicoes_detalhamento,statusProposicao.codSituacao,float64,23,0.383333,14,60
153,proposicoes_detalhamento,statusProposicao.despacho,str,0,0.000000,59,60
154,proposicoes_detalhamento,statusProposicao.url,str,46,0.766667,14,60
155,proposicoes_detalhamento,statusProposicao.ambito,str,0,0.000000,1,60
156,proposicoes_detalhamento,statusProposicao.apreciacao,str,0,0.000000,4,60
157,proposicoes_detalhamento,source_id,int64,0,0.000000,60,60
158,proposicoes_detalhamento,data_extracao,datetime64[us],0,0.000000,1,60

In [11]:
df_proposicoes_detalhamento = bronze.carregar_tabela('partidos_detalhamento')

✅ partidos_detalhamento: 15 linhas, 23 colunas

In [17]:
df_proposicoes_detalhamento['uriAutores'].iloc[1]

'https://dadosabertos.camara.leg.br/api/v2/proposicoes/618609/autores'

In [24]:
df_proposicoes_detalhamento[['codTipo','siglaTipo','descricaoTipo']].drop_duplicates()

    codTipo siglaTipo                                     descricaoTipo
0       139        PL                                    Projeto de Lei
7       134       MSC                                          Mensagem
8       610       DOC                                         Documento
9       291       MPV                                 Medida Provisória
20      720      PROC                                  Processo Interno
21     1033       DOC                      Ofício do Congresso Nacional
22      412       MSC             Mensagem de Restituição de Autógrafos
32      425       TVR               Permissão Rádio Frequência Modulada
33      401       MSC  Mensagem de Concessão ou Renovação de Rádio e TV
35      181        OF                                            Ofício
36      436       TVR                            Renovação TV Educativa
40      427       TVR                       Renovação Rádio Comunitária
58     1028       DOC                          Ofício do Senado Federal

In [23]:
df_proposicoes_detalhamento['ementa'].iloc[2]

'Altera o art. 121 do Decreto-Lei nº 2.848, de 7 de dezembro de 1940- Código Penal -  para prever como homicídio qualificado aquele praticado contra membros do Ministério Público e Magistratura, no exercício de sua função ou por causa dela e dá outras providências.\r\n\r\nNOVA EMENTA: Altera o Decreto-Lei nº 2.848, de 7 de dezembro de 1940 (Código Penal), e as Leis nºs 8.072, de 25 de julho de 1990 (Lei dos Crimes Hediondos), 12.694, de 24 julho de 2012, e 13.709, de 14 agosto de 2018 (Lei Geral de Proteção de Dados Pessoais), para reconhecer como atividade de risco permanente as atribuições inerentes ao Poder Judiciário e ao Ministério Público e garantir aos seus membros medidas de proteção, bem como recrudescer o tratamento penal destinado aos crimes de homicídio e de lesão corporal dolosa contra eles, desde que no exercício da função ou em decorrência dela, ou contra seu cônjuge, companheiro ou parente, inclusive por afinidade, até o terceiro grau, em razão dessa condição.'

In [41]:
df_proposicoes_detalhamento[
    df_proposicoes_detalhamento['keywords'].isnull()
][['ementa','keywords']]

                                               ementa keywords
8   ATA DA 30ª REUNIÃO EXTRAORDINÁRIA\nREALIZADA E...      NaN
14  Submete à apreciação do Congresso Nacional o t...      NaN
20  Propõe que a Comissão de Defesa do Consumidor ...      NaN
21  Comunica calendário de tramitação da MPV 1200/...      NaN
32  Submete à apreciação do Congresso Nacional o a...      NaN
33  Submete à apreciação do Congresso Nacional o a...      NaN
35  Ofício de Dispensa de Redação Final do PL 6399...      NaN
36  Submete à apreciação do Congresso Nacional o a...      NaN
37  Submete à apreciação do Congresso Nacional o a...      NaN
38  Submete à apreciação do Congresso Nacional o a...      NaN
39  Submete à apreciação do Congresso Nacional o a...      NaN
40  Submete à apreciação do Congresso Nacional o a...      NaN
41  Submete à apreciação do Congresso Nacional o a...      NaN
42  Submete à apreciação do Congresso Nacional o a...      NaN
43  Submete à apreciação do Congresso Nacional o a...      NaN
44  Submete à apreciação do Congresso Nacional o a...      NaN
46  Nos termos do art. 9 do Regimento Interno da C...      NaN
48  REPRESENTAÇÃO POR QUEBRA DE DECORO E ABUSO DE ...      NaN
58  Ofício SF 1447/2025 que comunica restituição d...      NaN
59  Ofício SF 1448/2025 que comunica restituição d...      NaN

In [ ]:
df_proposicoes_detalhamento[['ementa','keywords']]

In [35]:
df_analise[df_analise['tabela'] == 'tipos_proposicao']

,tabela,coluna,tipo,nulos,%_nulos,unicos,total_linhas
177,tipos_proposicao,cod,str,0,0.000000,544,544
178,tipos_proposicao,sigla,str,0,0.000000,182,544
179,tipos_proposicao,nome,str,0,0.000000,521,544
180,tipos_proposicao,descricao,str,3,0.005515,173,544
181,tipos_proposicao,data_extracao,datetime64[us],0,0.000000,1,544

In [37]:
df_tiposProposicao = dfs_bronze['tipos_proposicao']

In [39]:
display(df_tiposProposicao)

,cod,sigla,nome,descricao,data_extracao
0,27,OF,Ofício do Congresso Nacional,,2026-04-21 08:56:09.295878
1,129,CON,Consulta,Consulta,2026-04-21 08:56:09.295878
2,130,EMC,Emenda na Comissão,Emenda Apresentada na Comissão,2026-04-21 08:56:09.295878
3,131,EMP,Emenda de Plenário,Emenda de Plenário,2026-04-21 08:56:09.295878
4,132,EMS,Emenda/Substitutivo do Senado,Emenda/Substitutivo do Senado,2026-04-21 08:56:09.295878
...,...,...,...,...,...
539,1098,DOC,Ofício de Órgão da Câmara dos Deputados,,2026-04-21 08:56:09.295878
540,1099,ATA_PRE,Ata Preparatória,,2026-04-21 08:56:09.295878
541,1100,SAP,Sustação de Andamento de Ação Penal,,2026-04-21 08:56:09.295878
542,1101,REC,Recurso contra parecer terminativo do Conselho...,"Art. 14, § 4º, inciso III, do CEDP",2026-04-21 08:56:09.295878
543,1102,OFM,Ofício à Mesa,,2026-04-21 08:56:09.295878

In [42]:
df_proposicoesTemas = dfs_bronze['proposicoes_temas']

In [43]:
df_proposicoesTemas.sample(5)

,codTema,tema,relevancia,source_id,data_extracao
18,70,Finanças Públicas e Orçamento,0,2345498,2026-04-19 18:24:25.731797
61,41,Cidades e Desenvolvimento Urbano,0,2599898,2026-04-19 18:24:25.731797
40,70,Finanças Públicas e Orçamento,0,2599885,2026-04-19 18:24:25.731797
53,70,Finanças Públicas e Orçamento,0,2599894,2026-04-19 18:24:25.731797
52,40,Economia,0,2599894,2026-04-19 18:24:25.731797

In [47]:
#confirmando se há apenas um cod por tema


df_proposicoesTemas.groupby('codTema')['tema'].nunique()

codTema
34    1
37    1
40    1
41    1
42    1
43    1
44    1
46    1
48    1
52    1
54    1
55    1
56    1
57    1
58    1
62    1
64    1
66    1
70    1
72    1
76    1
Name: tema, dtype: int64

In [48]:
df_analise[df_analise['tabela'] == 'votacoes_detalhamento']

,tabela,coluna,tipo,nulos,%_nulos,unicos,total_linhas
182,votacoes_detalhamento,id,str,0,0.000000,271,271
183,votacoes_detalhamento,uri,str,0,0.000000,271,271
184,votacoes_detalhamento,data,str,0,0.000000,67,271
185,votacoes_detalhamento,dataHoraRegistro,str,0,0.000000,255,271
186,votacoes_detalhamento,siglaOrgao,str,0,0.000000,14,271
187,votacoes_detalhamento,uriOrgao,str,0,0.000000,16,271
188,votacoes_detalhamento,idOrgao,int64,0,0.000000,16,271
189,votacoes_detalhamento,uriEvento,str,65,0.239852,64,271
190,votacoes_detalhamento,idEvento,float64,65,0.239852,64,271
191,votacoes_detalhamento,descricao,str,0,0.000000,133,271
192,votacoes_detalhamento,aprovacao,float64,7,0.025830,2,271
193,votacoes_detalhamento,descUltimaAberturaVotacao,str,213,0.785978,31,271
194,votacoes_detalhamento,dataHoraUltimaAberturaVotacao,str,213,0.785978,56,271
195,votacoes_detalhamento,efeitosRegistrados,object,0,0.000000,72,271
196,votacoes_detalhamento,objetosPossiveis,object,0,0.000000,167,271
197,votacoes_detalhamento,proposicoesAfetadas,object,0,0.000000,26,271
198,votacoes_detalhamento,ultimaApresentacaoProposicao.dataHoraRegistro,str,66,0.243542,143,271
199,votacoes_detalhamento,ultimaApresentacaoProposicao.descricao,str,64,0.236162,146,271
200,votacoes_detalhamento,ultimaApresentacaoProposicao.uriProposicaoCitada,str,155,0.571956,59,271
201,votacoes_detalhamento,source_id,str,0,0.000000,271,271
202,votacoes_detalhamento,data_extracao,datetime64[us],0,0.000000,1,271

In [49]:
df_votacoes_detalhamento = dfs_bronze['votacoes_detalhamento']

display(df_votacoes_detalhamento)

,id,uri,data,dataHoraRegistro,siglaOrgao,uriOrgao,idOrgao,uriEvento,idEvento,descricao,...,descUltimaAberturaVotacao,dataHoraUltimaAberturaVotacao,efeitosRegistrados,objetosPossiveis,proposicoesAfetadas,ultimaApresentacaoProposicao.dataHoraRegistro,ultimaApresentacaoProposicao.descricao,ultimaApresentacaoProposicao.uriProposicaoCitada,source_id,data_extracao
0,369205-154,https://dadosabertos.camara.leg.br/api/v2/vota...,2023-08-09,2023-08-09T21:59:25,PLEN,https://dadosabertos.camara.leg.br/api/v2/orga...,180,https://dadosabertos.camara.leg.br/api/v2/even...,69153.0,Aprovada a Redação Final assinada pela Relator...,...,Votação da Redação Final.,2023-08-09T21:59:04,[],"[{'ano': 0, 'codTipo': 889, 'dataApresentacao'...","[{'ano': 2023, 'codTipo': 139, 'dataApresentac...",2023-08-10T13:04:07,Parecer às Emendas de Plenário proferido pela ...,https://dadosabertos.camara.leg.br/api/v2/prop...,369205-154,2026-04-19 18:53:12.134593
1,369205-151,https://dadosabertos.camara.leg.br/api/v2/vota...,2023-08-09,2023-08-09T21:58:06,PLEN,https://dadosabertos.camara.leg.br/api/v2/orga...,180,https://dadosabertos.camara.leg.br/api/v2/even...,69153.0,Aprovada a Subemenda Substitutiva Global ao Pr...,...,Votação em turno único.,2023-08-09T21:46:57,[],"[{'ano': 0, 'codTipo': 889, 'dataApresentacao'...","[{'ano': 2023, 'codTipo': 139, 'dataApresentac...",2023-08-10T13:04:07,Parecer às Emendas de Plenário proferido pela ...,https://dadosabertos.camara.leg.br/api/v2/prop...,369205-151,2026-04-19 18:53:12.134593
2,369205-129,https://dadosabertos.camara.leg.br/api/v2/vota...,2023-08-01,2023-08-01T20:17:21,PLEN,https://dadosabertos.camara.leg.br/api/v2/orga...,180,NaN,NaN,Alteração do Regime de Tramitação desta propos...,...,NaN,NaN,[],"[{'ano': 2017, 'codTipo': 304, 'dataApresentac...","[{'ano': 2023, 'codTipo': 139, 'dataApresentac...",2017-07-05T12:16:17,Apresentação do Requerimento de Apensação n. 6...,https://dadosabertos.camara.leg.br/api/v2/prop...,369205-129,2026-04-19 18:53:12.134593
3,369205-128,https://dadosabertos.camara.leg.br/api/v2/vota...,2023-08-01,2023-08-01T20:17:21,SECAP(SGM),https://dadosabertos.camara.leg.br/api/v2/orga...,100001,NaN,NaN,Realizar o encaminhamento do PL-2131/2007 à CI...,...,NaN,NaN,[],"[{'ano': 2017, 'codTipo': 304, 'dataApresentac...","[{'ano': 2023, 'codTipo': 139, 'dataApresentac...",NaN,NaN,NaN,369205-128,2026-04-19 18:53:12.134593
4,369205-127,https://dadosabertos.camara.leg.br/api/v2/vota...,2023-08-01,2023-08-01T20:17:17,SECAP(SGM),https://dadosabertos.camara.leg.br/api/v2/orga...,100001,NaN,NaN,Realizar o encaminhamento do PL-2131/2007 à CC...,...,NaN,NaN,[],"[{'ano': 2017, 'codTipo': 304, 'dataApresentac...","[{'ano': 2023, 'codTipo': 139, 'dataApresentac...",NaN,NaN,NaN,369205-127,2026-04-19 18:53:12.134593
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,2481882-23,https://dadosabertos.camara.leg.br/api/v2/vota...,2025-11-26,2025-11-26T15:57:14,CCOM,https://dadosabertos.camara.leg.br/api/v2/orga...,539385,https://dadosabertos.camara.leg.br/api/v2/even...,80291.0,Aprovado o Parecer.,...,NaN,NaN,[],"[{'ano': 0, 'codTipo': 190, 'dataApresentacao'...","[{'ano': 2025, 'codTipo': 436, 'dataApresentac...",2025-11-24T18:42:24,"Parecer do Relator, Dep. Rodrigo da Zaeli (PL-...",https://dadosabertos.camara.leg.br/api/v2/prop...,2481882-23,2026-04-19 18:53:12.134593
267,2481884-23,https://dadosabertos.camara.leg.br/api/v2/vota...,2025-10-22,2025-10-22T15:38:16,CCOM,https://dadosabertos.camara.leg.br/api/v2/orga...,539385,https://dadosabertos.camara.leg.br/api/v2/even...,79840.0,Aprovado o Parecer.,...,NaN,NaN,[],"[{'ano': 0, 'codTipo': 190, 'dataApresentacao'...","[{'ano': 2025, 'codTipo': 436, 'dataApresentac...",2025-10-20T15:05:53,"Parecer do Relator, Dep. Julio Cesar Ribeiro (...",https://dadosabertos.camara.leg.br/api/v2/prop...,2481884-23,2026-04-19 18:53:12.134593
268,2481886-23,https://dadosabertos.camara.leg.br/api/v2/vota...,2025-10-22,2025-10-22T15:38:17,CCOM,https://dadosabertos.camara.leg.br/api/v2/orga...,539385,https://dadosabertos.camara.leg.br/api/v2/even...,79840.0,Aprovado o Parecer.,...,NaN,NaN,[],"[{'ano': 0, 'codTipo': 190, 'dataApresentacao'...","[{'ano': 2025, 'codTipo': 427, 'dataApresentac...",2025-10-20T15:05:30,"Parecer do Relator, Dep. Rodrigo Estacho (PSD-...",https://dadosabertos.camara.leg.br/api/v2/prop...,2481886-23,2026-04-19 18:53:12.134593
269,2481888-23,https://dadosabertos.camara.leg.br/api/v2/vota...,2025-11-06,2025-11-06T12:02:33,CCOM,https://dadosabertos.camara.leg.br/api/v2/orga...,539385,https://dadosabertos.camara.leg.br/api/v2/even...,80236.0,Aprovado o Parecer.,...,NaN,NaN,[],"[{'ano': 0, 'codTipo': 190, 'dataApresentacao'...","[{'ano': 2025, 'codTipo': 427, 'dataApresentac...",2025-10-24T15:42:51,"Parecer do Relator, Dep. André Figueiredo (PDT...",https://dadosabertos.camara.leg.br/api/v2/prop...,2481888-23,2026-04-19 18:53:12.134593
270,2481890-23,https://dadosabertos.camara.leg.br/api/v2/vota...,2025-11-26,2025-11-26T15:57:15,CCOM,https://dadosabertos.camara.leg.br/api/v2/orga...,539385,https://dadosabertos.camara.leg.br/api/v2/even...,80291.0,Aprovado o Parecer.,...,NaN,NaN,[],"[{'ano': 0, 'codTipo': 190, 'dataApresentacao'...","[{'ano': 2025, 'codTipo': 427, 'dataApresentac...",2025-11-24T17:27:39,"Parecer do Relator, Dep. Gustavo Gayer (PL-GO)...",https://dadosabertos.camara.leg.br/api/v2/prop...,2481890-23,2026-04-19 18:53:12.134593

In [53]:
df_votacoes_detalhamento['objetosPossiveis'].iloc[5]

array([{'ano': 2017, 'codTipo': 304, 'dataApresentacao': '2017-07-05T11:34', 'ementa': 'Requer que seja apensado o Projeto de Lei nº 249/2015 ao Projeto de Lei nº 2.131/2007.', 'id': 2143693, 'numero': 6817, 'siglaTipo': 'REQ', 'uri': 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/2143693'}],
      dtype=object)

In [54]:
df_votacoes_detalhamento['source_id'].iloc[5]

'369205-126'

In [55]:
df_votacoes_detalhamento['proposicoesAfetadas'].iloc[5]

array([{'ano': 2023, 'codTipo': 139, 'dataApresentacao': '2007-09-26T12:37', 'ementa': 'Torna obrigatória a homologação em cartório de todo contrato de empréstimo consignado a ser efetuado por aposentado ou pensionista do INSS.  NOVA EMENTA: Altera as Leis nºs 10.820, de 17 de dezembro de 2003, e 14.509, de 27 de dezembro de 2022, para dispor sobre a concessão de crédito consignado sem autorização do beneficiário, e a Lei nº 10.741, de 1º de outubro de 2003 (Estatuto da Pessoa Idosa), para caracterizar como prática discriminatória a conduta que especifica.', 'id': 369205, 'numero': 4089, 'siglaTipo': 'PL', 'uri': 'https://dadosabertos.camara.leg.br/api/v2/proposicoes/369205'}],
      dtype=object)

In [56]:
df_votacoes_detalhamento['proposicoesAfetadas'].apply(len).value_counts()

proposicoesAfetadas
1    269
2      2
Name: count, dtype: int64

In [57]:
df_votacoes_orientacao = dfs_bronze['votacoes_orientacao']

In [58]:
df_votacoes_orientacao.sample(5)

,orientacaoVoto,codTipoLideranca,siglaPartidoBloco,codPartidoBloco,uriPartidoBloco,source_id,data_extracao
274,Não,B,Governo,NaN,NaN,1548579-122,2026-04-19 18:59:52.938521
154,Não,B,Fdr PT-PCdoB-PV,NaN,NaN,2345493-50,2026-04-19 18:59:52.938521
116,Sim,P,NOVO,37901.0,https://dadosabertos.camara.leg.br/api/v2/part...,2115253-116,2026-04-19 18:59:52.938521
269,Sim,B,Bl MdbPsdRepPode,NaN,NaN,1548579-126,2026-04-19 18:59:52.938521
285,Sim,B,Fdr PSOL-REDE,NaN,NaN,1548579-114,2026-04-19 18:59:52.938521