Transformação de dados

In [47]:
import pandas as pd
from camara_deputados.ingestion.data_loader import DataLoader
from camara_deputados.extraction.write import DataWrite
from camara_deputados.transformer.transformer import DataTransformer

In [48]:
# instâncias

bronze = DataLoader('bronze')
salva= DataWrite()
transforma = DataTransformer()

In [49]:
dfs_bronze = bronze.carregar_parquets()

📂 Lendo dados da camada bronze: /mnt/d/GabrielaTorres/estudos/Univesp_Projetos/pi_camara_deputados/notebooks/../data/bronze

✅ deputado_detalhamento: 1000 linhas, 34 colunas
✅ deputado_frentes: 271053 linhas, 6 colunas
✅ deputado_lista: 1000 linhas, 10 colunas
✅ frentes: 100 linhas, 5 colunas
✅ frentes_detalhamento: 100 linhas, 22 colunas
✅ partidos: 15 linhas, 5 colunas
✅ partidos_detalhamento: 15 linhas, 23 colunas
✅ proposicoes: 135 linhas, 10 colunas
✅ proposicoes_autores: 343 linhas, 8 colunas
✅ proposicoes_detalhamento: 135 linhas, 36 colunas
✅ proposicoes_temas: 141 linhas, 5 colunas
✅ proposicoes_votacoes: 819 linhas, 13 colunas
✅ tipos_Autor: 58 linhas, 5 colunas
✅ tipos_proposicao: 544 linhas, 5 colunas
✅ votacoes_detalhamento: 819 linhas, 21 colunas
✅ votacoes_orientacao: 1883 linhas, 7 colunas

🎯 Carregamento finalizado.

# Cria camada silver

## Deputado

In [51]:
# criando a silver Deputado

df_deputadoDetalhamento = dfs_bronze['deputado_detalhamento']

colunas_origem = list(df_deputadoDetalhamento)

In [53]:
#renomeado as colunas 

mapeamento_deputados = {
    'id':('id_Mandato','int')
    ,'nomeCivil':('nom_NomeCivil','str')
    ,'sexo':('nom_Sexo','str')
    ,'dataNascimento':('dat_DataNasc','date')
    ,'dataFalecimento':('dat_DataFalecimento','date')
    ,'ufNascimento':('nom_UFNasc','str')
    ,'municipioNascimento':('nom_MunicipioNasci','str')
    ,'escolaridade':('nom_Escolaridade','str')
    ,'ultimoStatus.siglaPartido':( 'nom_SiglaPartido','str')
    ,'ultimoStatus.siglaUf':('nom_UFRepresenta', 'str')
    ,'ultimoStatus.idLegislatura':('id_legislatura','int')
    ,'ultimoStatus.email':('nom_Email','str')
    ,'ultimoStatus.nomeEleitoral':('nom_NomeEleitoral','str')
    ,'ultimoStatus.situacao':('nom_Situacao','str')
    ,'ultimoStatus.condicaoEleitoral':('nom_CondEleitoral','str')
    ,'source_id': ('id_Deputado', 'int')

}

df_s_deputado = transforma.rename_and_cast(df_s_deputado,mapeamento_deputados)

In [55]:
salva.save_parquet(df_s_deputado, 'silver_deputado', 'silver')

💾 Salvo em: /mnt/d/GabrielaTorres/estudos/Univesp_Projetos/pi_camara_deputados/data/silver/silver_deputado/silver_deputado.parquet

## Deputados Frentes

In [57]:
df_deputadoFrentes = dfs_bronze['deputado_frentes']

In [58]:
print(df_deputadoFrentes.columns)

Index(['id', 'uri', 'titulo', 'idLegislatura', 'source_id', 'data_extracao'], dtype='str')

In [60]:
mapeamento_frentes = {
    'id': ('id_Frente', 'int'),
    #'uri': ('des_Uri', 'str'),
    'titulo': ('nom_Titulo', 'str'),
    'idLegislatura': ('id_Legislatura', 'int'),
    'source_id': ('id_Deputado', 'int'),
    #'data_extracao': ('dat_DataExtracao', 'datetime')
}

df_s_frenteDeputado = transforma.rename_and_cast(df_deputadoFrentes,mapeamento_frentes)

In [61]:
df_s_frenteDeputado.sample(5)

,id_Frente,nom_Titulo,id_Legislatura,id_Deputado
217718,54432,Frente Parlamentar Mista em Defesa da Advocaci...,57,160758
247883,54294,Frente Parlamentar Mista de Portos e Aeroportos,57,198783
46681,53952,Frente Parlamentar em Defesa da Polícia Federal,56,178881
18325,53995,Frente Parlamentar em Defesa do BANCO DO NORDE...,56,178836
54373,54080,Frente Parlamentar Mista da Mineração,56,74471

In [62]:
salva.save_parquet(df_s_frenteDeputado,'silver_frenteDeputado', 'silver')

💾 Salvo em: /mnt/d/GabrielaTorres/estudos/Univesp_Projetos/pi_camara_deputados/data/silver/silver_frenteDeputado/silver_frenteDeputado.parquet

## Proposicões Detalhada

In [63]:
#criando a tabela silver das proposições

df_proposicaoDetalhamento = dfs_bronze['proposicoes_detalhamento']

colunas_origem = list(df_proposicaoDetalhamento.columns)
print(colunas_origem)

['id', 'uri', 'siglaTipo', 'codTipo', 'numero', 'ano', 'ementa', 'dataApresentacao', 'uriOrgaoNumerador', 'uriAutores', 'descricaoTipo', 'ementaDetalhada', 'keywords', 'uriPropPrincipal', 'uriPropAnterior', 'uriPropPosterior', 'urlInteiroTeor', 'urnFinal', 'texto', 'justificativa', 'statusProposicao.dataHora', 'statusProposicao.sequencia', 'statusProposicao.siglaOrgao', 'statusProposicao.uriOrgao', 'statusProposicao.uriUltimoRelator', 'statusProposicao.regime', 'statusProposicao.descricaoTramitacao', 'statusProposicao.codTipoTramitacao', 'statusProposicao.descricaoSituacao', 'statusProposicao.codSituacao', 'statusProposicao.despacho', 'statusProposicao.url', 'statusProposicao.ambito', 'statusProposicao.apreciacao', 'source_id', 'data_extracao']

In [64]:
# as colunas sinalizadas com # não subirão para a silver

mapeamento_proposicao= {
    'id':('id_Proposicao','int')
    #,'uri'
    ,'siglaTipo':('nom_TipoProposicao','str')
    ,'codTipo':('cod_Tipo','int')
    ,'numero':('num_NumeroProp','int')
    ,'ano':('num_Ano', 'int')
    ,'ementa':('nom_Ementa','str')
    ,'dataApresentacao':('dat_Apresentacao','date')
    #,'uriOrgaoNumerador'
    ,'uriAutores':('uri_Autor','str')
    #,'descricaoTipo'
    #,'ementaDetalhada'
    ,'keywords':('nom_Keywords','str')
    #,'uriPropPrincipal'
    #,'uriPropAnterior'
    #,'uriPropPosterior'
    #,'urlInteiroTeor'
    #,'urnFinal'
    #,'texto'
    #,'justificativa'
    #,'statusProposicao.dataHora'
    #,'statusProposicao.sequencia'
    ,'statusProposicao.siglaOrgao':('nom_SiglaOrgao', 'str')
    #,'statusProposicao.uriOrgao'
    ,'statusProposicao.uriUltimoRelator':('uri_Relator', 'str')
    ,'statusProposicao.regime':('nom_regime','str')
    ,'statusProposicao.descricaoTramitacao':('nom_TipoTramitacao','str')
    ,'statusProposicao.codTipoTramitacao':('cod_TipoTramitacao','int')
    ,'statusProposicao.descricaoSituacao':('cod_TipoSiituacao','str')
    ,'statusProposicao.codSituacao':('cod_Situacao','int')
    #,'statusProposicao.despacho'
    ,'statusProposicao.url':('nom_LinkProposicao','str')
    #,'statusProposicao.ambito'
    #,'statusProposicao.apreciacao'
    #,'source_id'
    #,'data_extracao'
}

df_s_proposicao = transforma.rename_and_cast(df_proposicaoDetalhamento, mapeamento_proposicao)

In [65]:
# Pega o id da uri

colunas_uri = {'uri_Autor':('nom_TipoAutor','id_Autor'), 'uri_Relator':('nom_TipoRelator','id_Relator')}

df_s_proposicao = transforma.extrair_tipos_e_ids(df_s_proposicao, colunas_uri)

In [66]:
df_s_proposicao.info()

<class 'pandas.DataFrame'>
RangeIndex: 135 entries, 0 to 134
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_Proposicao       135 non-null    Int64
 1   nom_TipoProposicao  135 non-null    string
 2   cod_Tipo            135 non-null    Int64
 3   num_NumeroProp      135 non-null    Int64
 4   num_Ano             135 non-null    Int64
 5   nom_Ementa          135 non-null    string
 6   dat_Apresentacao    135 non-null    datetime64[us]
 7   uri_Autor           135 non-null    string
 8   nom_Keywords        105 non-null    string
 9   nom_SiglaOrgao      133 non-null    string
 10  uri_Relator         85 non-null     string
 11  nom_regime          135 non-null    string
 12  nom_TipoTramitacao  133 non-null    string
 13  cod_TipoTramitacao  133 non-null    Int64
 14  cod_TipoSiituacao   101 non-null    string
 15  cod_Situacao        101 non-null    Int64
 16  nom_LinkProposicao  35 non-null     string
 17  nom_TipoAutor       135 non-null    str
 18  id_Autor            135 non-null    Int64
 19  nom_TipoRelator     85 non-null     str
 20  id_Relator          85 non-null     Int64
dtypes: Int64(8), datetime64[us](1), str(2), string(10)
memory usage: 108.1 KB

In [67]:
# salva as proposições na silver

salva.save_parquet(df_s_proposicao, 'silver_proposicao','silver')

💾 Salvo em: /mnt/d/GabrielaTorres/estudos/Univesp_Projetos/pi_camara_deputados/data/silver/silver_proposicao/silver_proposicao.parquet

## Autores Proposicões

In [68]:
df_proposicaoAutores = dfs_bronze['proposicoes_autores']

mapeamento_autores = list(df_proposicaoAutores.columns)

In [69]:
mapeamento_autores = {
    'uri': ('uri_Autor', 'str'),
    'nome': ('nom_Autor', 'str'),
    'codTipo': ('cod_TipoAutor', 'int'),
    'tipo': ('nom_TipoAutor', 'str'),
    'ordemAssinatura': ('num_OrdemAssinatura', 'int'),
    'proponente': ('ind_Proponente', 'str'),  
    'source_id': ('id_Proposicao', 'int'),
    'data_extracao': ('dat_Extracao', 'date')
}

df_s_autores  = transforma.rename_and_cast(df_proposicaoAutores, mapeamento_autores)

## Resgata ID da uri

df_s_autores = transforma.extrair_tipos_e_ids(
    df_s_autores,
    {
        'uri_Autor': ('nom_TipoAutor', 'id_Autor')
    }
)

In [70]:
df_s_autores.columns

Index(['uri_Autor', 'nom_Autor', 'cod_TipoAutor', 'nom_TipoAutor',
       'num_OrdemAssinatura', 'ind_Proponente', 'id_Proposicao',
       'dat_Extracao', 'id_Autor'],
      dtype='str')

In [22]:
df_s_autores.sample(20)

,uri_Autor,nom_Autor,cod_TipoAutor,nom_TipoAutor,num_OrdemAssinatura,ind_Proponente,id_proposicao,dat_Extracao,id_Autor
7,https://dadosabertos.camara.leg.br/api/v2/orga...,Poder Executivo,30000,orgaos,1,1,2345487,2026-04-19 18:19:55.573900,253
4,https://dadosabertos.camara.leg.br/api/v2/depu...,Mara Gabrilli,10000,deputados,1,1,2074843,2026-04-19 18:19:55.573900,160565
26,https://dadosabertos.camara.leg.br/api/v2/orga...,Poder Executivo,30000,orgaos,1,1,2416825,2026-04-19 18:19:55.573900,253
31,https://dadosabertos.camara.leg.br/api/v2/orga...,Poder Executivo,30000,orgaos,1,1,2481877,2026-04-19 18:19:55.573900,253
12,https://dadosabertos.camara.leg.br/api/v2/orga...,Senado Federal - Roberto Muniz,40000,orgaos,1,1,2345498,2026-04-19 18:19:55.573900,78
17,https://dadosabertos.camara.leg.br/api/v2/depu...,Sandro Alex,10000,deputados,1,1,2092056,2026-04-19 18:19:55.573900,160621
6,https://dadosabertos.camara.leg.br/api/v2/orga...,Poder Executivo,30000,orgaos,1,1,2345485,2026-04-19 18:19:55.573900,253
9,https://dadosabertos.camara.leg.br/api/v2/orga...,Poder Executivo,30000,orgaos,1,1,2345494,2026-04-19 18:19:55.573900,253
41,https://dadosabertos.camara.leg.br/api/v2/orga...,Poder Executivo,30000,orgaos,1,1,2481889,2026-04-19 18:19:55.573900,253
50,https://dadosabertos.camara.leg.br/api/v2/orga...,Poder Executivo,30000,orgaos,1,1,2599894,2026-04-19 18:19:55.573900,253
2,https://dadosabertos.camara.leg.br/api/v2/depu...,Evandro Rogerio Roman,10000,deputados,1,1,1197773,2026-04-19 18:19:55.573900,178930
23,https://dadosabertos.camara.leg.br/api/v2/orga...,Poder Executivo,30000,orgaos,1,1,2416822,2026-04-19 18:19:55.573900,253
39,https://dadosabertos.camara.leg.br/api/v2/orga...,Poder Executivo,30000,orgaos,1,1,2481887,2026-04-19 18:19:55.573900,253
40,https://dadosabertos.camara.leg.br/api/v2/orga...,Poder Executivo,30000,orgaos,1,1,2481888,2026-04-19 18:19:55.573900,253
35,https://dadosabertos.camara.leg.br/api/v2/orga...,Poder Executivo,30000,orgaos,1,1,2481883,2026-04-19 18:19:55.573900,253
11,https://dadosabertos.camara.leg.br/api/v2/orga...,Poder Executivo,30000,orgaos,1,1,2345496,2026-04-19 18:19:55.573900,253
42,https://dadosabertos.camara.leg.br/api/v2/orga...,Poder Executivo,30000,orgaos,1,1,2481890,2026-04-19 18:19:55.573900,253
45,https://dadosabertos.camara.leg.br/api/v2/orga...,Poder Executivo,30000,orgaos,1,1,2599888,2026-04-19 18:19:55.573900,253
32,https://dadosabertos.camara.leg.br/api/v2/orga...,Poder Executivo,30000,orgaos,1,1,2481880,2026-04-19 18:19:55.573900,253
24,https://dadosabertos.camara.leg.br/api/v2/orga...,Poder Executivo,30000,orgaos,1,1,2416823,2026-04-19 18:19:55.573900,253

In [72]:
salva.save_parquet(df_s_autores, 'silver_autores','silver')

💾 Salvo em: /mnt/d/GabrielaTorres/estudos/Univesp_Projetos/pi_camara_deputados/data/silver/silver_autores/silver_autores.parquet

## Silver temas das proposicoes

In [73]:
df_proposicoesTemas = dfs_bronze['proposicoes_temas']

list_temas = list(df_proposicoesTemas.columns)

mapeamento_temas = {
    'codTema': ('cod_Tema', 'int'),
    'tema': ('nom_Tema', 'str'),
    'relevancia': ('num_Relevancia', 'int'),
    'source_id': ('id_proposicao', 'int'),
    'data_extracao': ('dat_Extracao', 'date')
}

df_s_temasProposicoes = transforma.rename_and_cast(df_proposicoesTemas,mapeamento_temas)

In [74]:
salva.save_parquet(df_s_temasProposicoes, 'silver_temasProposicao', 'silver')

💾 Salvo em: /mnt/d/GabrielaTorres/estudos/Univesp_Projetos/pi_camara_deputados/data/silver/silver_temasProposicao/silver_temasProposicao.parquet

## Proposições votações

In [75]:
df_proposicoesVotacoes = dfs_bronze['proposicoes_votacoes']

In [76]:
print(list(df_proposicoesVotacoes.columns))

['id', 'uri', 'data', 'dataHoraRegistro', 'siglaOrgao', 'uriOrgao', 'uriEvento', 'proposicaoObjeto', 'uriProposicaoObjeto', 'descricao', 'aprovacao', 'source_id', 'data_extracao']

In [83]:
mapeamento_votacao = {
    'id': ('id_Votacao', 'str'),
    #'uri': ('uri_Votacao', 'str'),
    'data': ('dat_DataVotacao', 'date'),
    'dataHoraRegistro': ('dat_DataRegistro', 'date'),
    #'siglaOrgao': ('nom_SiglaOrgao', 'str'),
    'uriOrgao': ('uri_Orgao', 'str'),
    #'uriVotacao': ('uri_votacaoDetalhe', 'str'),
    #'proposicaoObjeto': ('nom_ProposicaoObjeto', 'str'),
    #'uriProposicaoObjeto': ('uri_Proposicao', 'str'),
    'descricao': ('nom_Descricao', 'str'),
    'aprovacao': ('ind_Aprovado', 'str'),  
    'source_id': ('id_Proposicao', 'int'),
    #'data_extracao': ('dat_Extracao', 'date')
}

df_s_votacaoProposicao = transforma.rename_and_cast(df_proposicoesVotacoes,mapeamento_votacao)

In [84]:
df_s_votacaoProposicao = transforma.extrair_ids(
    df_s_votacaoProposicao,
    {'uri_Orgao': 'id_Orgao'}
)

In [85]:
salva.save_parquet(df_s_votacaoProposicao, 'silver_votacao_proposicao','silver')

💾 Salvo em: /mnt/d/GabrielaTorres/estudos/Univesp_Projetos/pi_camara_deputados/data/silver/silver_votacao_proposicao/silver_votacao_proposicao.parquet

## Votacões

In [86]:
df_votacaoDetalhamento = dfs_bronze['votacoes_detalhamento']

In [87]:
df_votacaoDetalhamento.head()

,id,uri,data,dataHoraRegistro,siglaOrgao,uriOrgao,idOrgao,uriEvento,idEvento,descricao,...,descUltimaAberturaVotacao,dataHoraUltimaAberturaVotacao,efeitosRegistrados,objetosPossiveis,proposicoesAfetadas,ultimaApresentacaoProposicao.dataHoraRegistro,ultimaApresentacaoProposicao.descricao,ultimaApresentacaoProposicao.uriProposicaoCitada,source_id,data_extracao
0,2167556-58,https://dadosabertos.camara.leg.br/api/v2/vota...,2018-05-23,2018-05-23T18:53:32,PLEN,https://dadosabertos.camara.leg.br/api/v2/orga...,180,https://dadosabertos.camara.leg.br/api/v2/even...,52773.0,Aprovada a Redação Final assinada pelo Relator...,...,Votação da Redação Final.,2018-05-23T18:53:00,[],"[{'ano': 0, 'codTipo': 197, 'dataApresentacao'...","[{'ano': 2018, 'codTipo': 291, 'dataApresentac...",2018-05-09T16:30:50,Apresentação do Requerimento de Inclusão na Or...,https://dadosabertos.camara.leg.br/api/v2/prop...,2167556-58,2026-05-01 14:34:11.672524
1,2167556-56,https://dadosabertos.camara.leg.br/api/v2/vota...,2018-05-23,2018-05-23T18:52:29,PLEN,https://dadosabertos.camara.leg.br/api/v2/orga...,180,https://dadosabertos.camara.leg.br/api/v2/even...,52773.0,"Aprovada a Medida Provisória nº 817 de 2018, n...",...,"Votação, quanto ao mérito, em turno único.",2018-05-23T18:48:51,[],"[{'ano': 0, 'codTipo': 197, 'dataApresentacao'...","[{'ano': 2018, 'codTipo': 291, 'dataApresentac...",2018-05-09T16:30:50,Apresentação do Requerimento de Inclusão na Or...,https://dadosabertos.camara.leg.br/api/v2/prop...,2167556-56,2026-05-01 14:34:11.672524
2,2167556-54,https://dadosabertos.camara.leg.br/api/v2/vota...,2018-05-23,2018-05-23T18:48:37,PLEN,https://dadosabertos.camara.leg.br/api/v2/orga...,180,https://dadosabertos.camara.leg.br/api/v2/even...,52773.0,"Aprovado, em apreciação preliminar, o Parecer ...",...,Votação preliminar em turno único.,2018-05-23T18:42:26,[],"[{'ano': 0, 'codTipo': 197, 'dataApresentacao'...","[{'ano': 2018, 'codTipo': 291, 'dataApresentac...",2018-05-09T16:30:50,Apresentação do Requerimento de Inclusão na Or...,https://dadosabertos.camara.leg.br/api/v2/prop...,2167556-54,2026-05-01 14:34:11.672524
3,2167559-66,https://dadosabertos.camara.leg.br/api/v2/vota...,2018-05-23,2018-05-23T20:50:02,PLEN,https://dadosabertos.camara.leg.br/api/v2/orga...,180,https://dadosabertos.camara.leg.br/api/v2/even...,52781.0,Suprimido o texto.,...,"Votação do art. 10-A, da Lei nº12.587/2012, co...",2018-05-23T20:29:59,[],"[{'ano': 2018, 'codTipo': 450, 'dataApresentac...","[{'ano': 2018, 'codTipo': 291, 'dataApresentac...",NaN,NaN,NaN,2167559-66,2026-05-01 14:34:11.672524
4,2167559-60,https://dadosabertos.camara.leg.br/api/v2/vota...,2018-05-23,2018-05-23T20:33:46,PLEN,https://dadosabertos.camara.leg.br/api/v2/orga...,180,https://dadosabertos.camara.leg.br/api/v2/even...,52781.0,Aprovada a Redação Final assinada pelo Relator...,...,Votação da Redação Final.,2018-05-23T20:35:58,[],"[{'ano': 2018, 'codTipo': 450, 'dataApresentac...","[{'ano': 2018, 'codTipo': 291, 'dataApresentac...",NaN,NaN,NaN,2167559-60,2026-05-01 14:34:11.672524

In [88]:
mapeamento_votacaoDetalhamento = {
    'id': ('id_Votacao', 'str'),
    #'uri': ('des_UriVotacao', 'str'),
    'data': ('dat_DataVotacao', 'date'),
    'dataHoraRegistro': ('dat_DataHoraRegistro', 'date'),
    
    'siglaOrgao': ('nom_SiglaOrgao', 'str'),
    #'uriOrgao': ('des_UriOrgao', 'str'),
    'idOrgao': ('id_Orgao', 'int'),
    
    #'uriEvento': ('des_UriEvento', 'str'),
    'idEvento': ('id_Evento', 'int'),
    
    'descricao': ('des_DescricaoVotacao', 'str'),
    'aprovacao': ('ind_Aprovacao', 'str'),
    
    'descUltimaAberturaVotacao': ('des_UltimaAbertura', 'str'),
    'dataHoraUltimaAberturaVotacao': ('dat_UltimaAbertura', 'date'),
    
    'efeitosRegistrados': ('des_Efeitos', 'str'),
    'objetosPossiveis': ('des_Objetos', 'str'),
    'proposicoesAfetadas': ('des_Proposicoes', 'str'),
    
    'ultimaApresentacaoProposicao.dataHoraRegistro': ('dat_UltimaApresentacao', 'date'),
    'ultimaApresentacaoProposicao.descricao': ('des_UltimaApresentacaoDesc', 'str'),
    'ultimaApresentacaoProposicao.uriProposicaoCitada': ('des_UriProposicao', 'str'),
    
    'source_id': ('id_Proposicao', 'str'),
    #'data_extracao': ('dat_DataExtracao', 'date')
}

In [89]:
df_s_votacoesDetalhamento = transforma.rename_and_cast(df_votacaoDetalhamento,mapeamento_votacaoDetalhamento)

df_s_votacoesDetalhamento = transforma.explode_and_extract(df_s_votacoesDetalhamento, 
                                                           'id',
                                                           {'id':'id_ProposicaoAfetada'})

In [90]:
df_s_votacoesDetalhamento.info()

<class 'pandas.DataFrame'>
RangeIndex: 819 entries, 0 to 818
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id_Votacao                  819 non-null    string
 1   dat_DataVotacao             819 non-null    datetime64[us]
 2   dat_DataHoraRegistro        819 non-null    datetime64[us]
 3   nom_SiglaOrgao              819 non-null    string
 4   id_Orgao                    819 non-null    Int64
 5   id_Evento                   732 non-null    Int64
 6   des_DescricaoVotacao        819 non-null    string
 7   ind_Aprovacao               797 non-null    string
 8   des_UltimaAbertura          193 non-null    string
 9   dat_UltimaAbertura          193 non-null    datetime64[us]
 10  des_Efeitos                 819 non-null    string
 11  des_Objetos                 819 non-null    string
 12  des_Proposicoes             819 non-null    string
 13  dat_UltimaApresentacao      694 non-null    datetime64[us]
 14  des_UltimaApresentacaoDesc  717 non-null    string
 15  des_UriProposicao           412 non-null    string
 16  id_Proposicao               819 non-null    string
dtypes: Int64(2), datetime64[us](4), string(11)
memory usage: 5.3 MB

In [91]:
salva.save_parquet(df_s_votacoesDetalhamento, 'silver_votacao_detalhamento','silver')

💾 Salvo em: /mnt/d/GabrielaTorres/estudos/Univesp_Projetos/pi_camara_deputados/data/silver/silver_votacao_detalhamento/silver_votacao_detalhamento.parquet

## Votações Orientação

In [92]:
df_votacoesOrientacao = dfs_bronze['votacoes_orientacao']

In [93]:
mapeamento_orientacaoVoto = {
    'orientacaoVoto': ('nom_OrientacaoVoto', 'str'),
    'codTipoLideranca': ('id_TipoLideranca', 'int'),
    
    'siglaPartidoBloco': ('nom_SiglaPartidoBloco', 'str'),
    'codPartidoBloco': ('id_PartidoBloco', 'int'),
    'uriPartidoBloco': ('des_UriPartidoBloco', 'str'),
    
    'source_id': ('id_Votacao', 'str'),
    'data_extracao': ('dat_DataExtracao', 'date')
}

df_s_votosOrientacao = transforma.rename_and_cast(df_votacoesOrientacao,
                                                mapeamento_orientacaoVoto)

In [94]:
df_tiposAutor = dfs_bronze['tipos_Autor']

In [95]:
df_tiposAutor.columns

Index(['cod', 'sigla', 'nome', 'descricao', 'data_extracao'], dtype='str')

In [96]:
maping_autor = {'cod':('id_Autor','int'),
 #'sigla',
 'nome':('nom_NomeAutor','str'),
 #'descricao',
 #'data_extracao'
}



s_tiposAutores = transforma.rename_and_cast(
    df_tiposAutor,
    maping_autor,
)

In [97]:
salva.save_parquet(
    s_tiposAutores,
    'silver_tipos_autores',
    'silver'
)

💾 Salvo em: /mnt/d/GabrielaTorres/estudos/Univesp_Projetos/pi_camara_deputados/data/silver/silver_tipos_autores/silver_tipos_autores.parquet